"""Question engine for the guided chat.

Turns "these three look identical, you pick" into a short series of
answerable questions.

Visual similarity cannot separate parts that genuinely look alike — two
brake pad sets for different cars are the same object photographed twice.
But the catalog already knows what does separate them: fitment and brand.
So instead of asking the user to compare photos they have no way to
judge, ask what they actually know ("which vehicle?") and let each answer
eliminate candidates.

Questions are derived from catalog metadata rather than generated by
Brain 4: every option is guaranteed to correspond to real SKUs, an answer
provably narrows the set, and it works with the LLM switched off.

This is a faithful port of `frontend/src/services/disambiguation.ts` —
the two must stay behaviourally in step, since mock mode runs the
TypeScript version and live mode runs this one.
"""

from dataclasses import dataclass, field

#: Similarity gap between rank 1 and rank 2 above which the photo is said
#: to have a decisive favourite. Mirrors `STRONG_SEPARATION_GAP` in
#: `frontend/src/services/identificationService.ts` — keep in sync.
STRONG_SEPARATION_GAP = 0.08

#: Attribute keys that name a sub-type of the part itself (e.g. "air
#: strut" vs "shock absorber") rather than an independent trait. These
#: overlap with the classification the app exists to do — asking the user
#: to tell them apart would just outsource that job back to them.
IDENTITY_ATTRIBUTE_KEYS = {"damper_style", "manifold_style"}

_PROMPTS: dict[str, tuple[str, str]] = {
    "make": ("Which vehicle is this part for?", "These candidates fit different makes."),
    "model": ("Which model?", "Narrowing further by model."),
    "year": ("Which model year?", "The remaining candidates cover different year ranges."),
    "mpn": (
        "Is one of these numbers on the part?",
        "Usually stamped into the metal or printed on the old box.",
    ),
    "brand": (
        "Do you know the part brand?",
        "Often stamped on the part or printed on the old packaging.",
    ),
}

_ATTRIBUTE_PROMPTS: dict[str, tuple[str, str]] = {
    "primary_colour": ("What colour is it, mainly?", "The body, not the fittings."),
    "filter_style": ("Is it a spin-on canister or a cartridge insert?", "Look at the shape."),
    "filter_shape": ("What shape is the filter?", ""),
    "position": ("Where does it fit on the vehicle?", "Front or rear axle."),
    "material": ("What is it made of?", ""),
    "friction_material": (
        "What is the friction material?",
        "Usually printed on the pad edge or box.",
    ),
    "injector_type": ("Which type of injector is it?", ""),
    "pump_style": ("Which type of pump is it?", ""),
    "throttle_control": (
        "Is it cable-operated or electronic?",
        "Look for a cable pulley or a plug.",
    ),
    "sold_as": ("How many are in the set?", ""),
    "lug_count": ("How many wheel studs does it have?", "Count the bolts on the flange."),
    "abs_sensor": ("Does it have an ABS sensor?", "A wire running off the hub."),
    "wear_sensor": ("Does it have a wear sensor?", "A small wire clipped to one pad."),
    "pulley_fitted": ("Is the pulley already fitted?", ""),
    "integrated_reservoir": ("Does it have a fluid reservoir on top?", ""),
    "catalytic_converter": ("Does it include a catalytic converter?", ""),
}

#: Attribute value slugs whose hyphen joins words rather than being part
#: of the term — mirrors `VALUE_LABELS` in `frontend/src/utils/attributes.ts`.
_VALUE_LABELS: dict[str, str] = {
    "strut-assembly": "Strut assembly",
    "shock-absorber": "Shock absorber",
    "remote-reservoir": "Remote reservoir",
    "air-strut": "Air strut",
    "long-tube-header": "Long-tube header",
    "shorty-header": "Shorty header",
    "oem-manifold": "OEM manifold",
    "direct-injection": "Direct injection",
    "common-rail": "Common rail",
    "dual-fuel": "Dual fuel",
    "unit-injector": "Unit injector",
    "stainless-steel": "Stainless steel",
    "cast-iron": "Cast iron",
    "yes": "Yes",
    "no": "No",
}

_KEY_LABELS: dict[str, str] = {
    "primary_colour": "Colour",
    "sold_as": "Sold as",
    "abs_sensor": "ABS sensor",
    "lug_count": "Wheel studs",
    "mpn": "Part number",
}


@dataclass(frozen=True)
class FitmentRange:
    """One contiguous run of model years a SKU fits, e.g. Ford Focus 2012–2018."""

    make: str
    model: str
    year_start: int
    year_end: int


@dataclass(frozen=True)
class ChatCandidate:
    """One catalog SKU still in play, with the facts questions draw on."""

    sku: str
    product_name: str
    brand: str
    similarity: float
    manufacturer_part_number: str | None = None
    #: Visual facts (`filter_style`, `position`, …) — what the user can
    #: answer by looking at the part in their hand.
    attributes: dict[str, str] = field(default_factory=dict)
    fitment: tuple[FitmentRange, ...] = ()


@dataclass(frozen=True)
class RowFilter:
    """The fitment rows an answer keeps in play.

    A product can fit several vehicles, so answering "Honda" must not only
    drop Toyota-only candidates — it must also stop a surviving candidate's
    Toyota rows from feeding the next question.
    """

    make: str | None = None
    model: str | None = None
    year_start: int | None = None
    year_end: int | None = None


@dataclass(frozen=True)
class Option:
    """One choice the user can tap. `skus` is never empty."""

    label: str
    skus: tuple[str, ...]
    row_filter: RowFilter | None = None


@dataclass(frozen=True)
class Question:
    facet: str
    prompt: str
    hint: str
    options: tuple[Option, ...]


@dataclass(frozen=True)
class Answer:
    """A recorded answer — the facet, what the user picked, and its effect."""

    facet: str
    label: str
    skus: tuple[str, ...]
    row_filter: RowFilter | None = None


@dataclass(frozen=True)
class VisualMismatch:
    """The photo's decisive pick vs. the best candidate the answers left alive."""

    visual_leader: ChatCandidate
    best_survivor: ChatCandidate


def format_attribute_label(key: str) -> str:
    """`filter_style` -> "Filter style"."""
    if key in _KEY_LABELS:
        return _KEY_LABELS[key]
    words = key.replace("_", " ").replace("-", " ").strip()
    return words[:1].upper() + words[1:]


def format_attribute_value(value: str) -> str:
    """`semi-metallic` -> "Semi-metallic"; `strut-assembly` -> "Strut assembly"."""
    return _VALUE_LABELS.get(value, value[:1].upper() + value[1:])


def prompt_for(facet: str) -> tuple[str, str]:
    """(prompt, hint) for a facet. `attr:<key>` facets fall back to a
    humanized key, so a new catalog attribute asks a sensible question
    without a code change."""
    if not facet.startswith("attr:"):
        return _PROMPTS[facet]
    key = facet.removeprefix("attr:")
    return _ATTRIBUTE_PROMPTS.get(
        key,
        (f"What's the {format_attribute_label(key).lower()}?", "Compare against the part in your photo."),
    )


def _unique_sorted(values: list[str]) -> list[str]:
    return sorted(set(values))


@dataclass(frozen=True)
class _Row:
    """One (SKU, vehicle-range) pair. Fitment is many-per-SKU, so questions
    filter rows, not products."""

    sku: str
    make: str
    model: str
    year_start: int
    year_end: int


def _fitment_rows(candidates: list[ChatCandidate]) -> list[_Row]:
    return [
        _Row(c.sku, r.make, r.model, r.year_start, r.year_end)
        for c in candidates
        for r in c.fitment
    ]


def _filter_rows(rows: list[_Row], answers: list[Answer]) -> list[_Row]:
    """Rows still consistent with every answer given so far."""
    for answer in answers:
        f = answer.row_filter
        if f is None:
            continue
        rows = [
            row
            for row in rows
            if (f.make is None or row.make == f.make)
            and (f.model is None or row.model == f.model)
            # Year answers are ranges; a row survives if its coverage overlaps.
            and (
                f.year_start is None
                or f.year_end is None
                or (row.year_start <= f.year_end and row.year_end >= f.year_start)
            )
        ]
    return rows


def _options_from_rows(rows: list[_Row], key: str) -> list[Option]:
    """Options for a facet whose values are plain strings on the fitment row."""
    values = _unique_sorted([getattr(row, key) for row in rows])
    return [
        Option(
            label=value,
            skus=tuple(_unique_sorted([row.sku for row in rows if getattr(row, key) == value])),
            row_filter=RowFilter(**{key: value}),
        )
        for value in values
    ]


def _year_options(rows: list[_Row]) -> list[Option]:
    """Year options as ranges rather than one chip per year.

    A year only distinguishes candidates where their coverage differs, so
    consecutive years matching the same SKU set collapse into a single chip —
    "2018–2022" and "2023–2024" rather than seven chips that mostly do nothing.
    """
    if not rows:
        return []
    first = min(row.year_start for row in rows)
    last = max(row.year_end for row in rows)

    runs: list[dict] = []
    for year in range(first, last + 1):
        skus = _unique_sorted(
            [row.sku for row in rows if row.year_start <= year <= row.year_end]
        )
        if not skus:
            continue
        previous = runs[-1] if runs else None
        if previous and previous["end"] == year - 1 and previous["skus"] == skus:
            previous["end"] = year
        else:
            runs.append({"start": year, "end": year, "skus": skus})

    return [
        Option(
            label=str(run["start"]) if run["start"] == run["end"] else f"{run['start']}–{run['end']}",
            skus=tuple(run["skus"]),
            row_filter=RowFilter(year_start=run["start"], year_end=run["end"]),
        )
        for run in runs
    ]


def _brand_options(candidates: list[ChatCandidate]) -> list[Option]:
    return [
        Option(
            label=brand,
            skus=tuple(_unique_sorted([c.sku for c in candidates if c.brand == brand])),
        )
        for brand in _unique_sorted([c.brand for c in candidates])
    ]


def _part_number_options(candidates: list[ChatCandidate]) -> list[Option]:
    numbered = [c for c in candidates if c.manufacturer_part_number]
    return [
        Option(
            label=mpn,
            skus=tuple(
                _unique_sorted([c.sku for c in numbered if c.manufacturer_part_number == mpn])
            ),
        )
        for mpn in _unique_sorted([c.manufacturer_part_number for c in numbered])  # type: ignore[list-item]
    ]


def _attribute_options(candidates: list[ChatCandidate], key: str) -> list[Option]:
    """One option per distinct value of an attribute key.

    Only offered when every candidate carries the key: a product whose
    attribute was never derived would otherwise be silently ruled out for
    having no value, which is a data gap rather than a mismatch.
    """
    if not all(c.attributes.get(key) for c in candidates):
        return []
    return [
        Option(
            label=format_attribute_value(value),
            skus=tuple(_unique_sorted([c.sku for c in candidates if c.attributes.get(key) == value])),
        )
        for value in _unique_sorted([c.attributes[key] for c in candidates])
    ]


def _worst_case_remaining(options: list[Option]) -> int:
    return max(len(option.skus) for option in options)


def _is_useful(options: list[Option], candidate_count: int) -> bool:
    """Worth asking if at least one answer rules something out.

    Deliberately not "every answer narrows it": a part fitting 2018–2024
    against one fitting 2018–2022 is only separated by picking 2023–24, and
    that question is still the one worth asking.
    """
    return len(options) > 1 and min(len(o.skus) for o in options) < candidate_count


def _answerability(facet: str) -> int:
    """How readily a typical user can answer, lowest first.

    Ranking purely by elimination power puts brand first, because brand
    usually splits the candidates perfectly — but someone photographing a
    part to find out what it is is exactly the person who does not know its
    brand. Visual attributes come first (answered by looking at the part in
    hand), then facts about their own car, then the part number, brand last.
    """
    if facet.startswith("attr:"):
        return 0
    return {"make": 1, "model": 2, "year": 3, "mpn": 4, "brand": 5}.get(facet, 9)


def apply_answers(candidates: list[ChatCandidate], answers: list[Answer]) -> list[ChatCandidate]:
    """Candidates still possible after every answer so far."""
    remaining = candidates
    for answer in answers:
        remaining = [c for c in remaining if c.sku in answer.skus]
    return remaining


def next_question(
    candidates: list[ChatCandidate],
    answers: list[Answer],
    skipped: list[str],
) -> Question | None:
    """The next question to ask, or None when the candidates are already
    resolved (or nothing left can separate them — the caller should fall
    back to manual choice)."""
    remaining = apply_answers(candidates, answers)
    if len(remaining) < 2:
        return None

    asked = [answer.facet for answer in answers] + list(skipped)
    rows = _filter_rows(_fitment_rows(remaining), answers)
    return _question_for(remaining, rows, asked)


def _question_for(
    candidates: list[ChatCandidate],
    rows: list[_Row],
    asked: list[str],
) -> Question | None:
    # A vehicle question can only eliminate safely when every candidate has
    # fitment on record. Otherwise "no rows" would look like "does not fit"
    # and silently rule out a product whose data is merely missing.
    every_candidate_has_fitment = all(c.fitment for c in candidates)

    built: list[tuple[str, list[Option]]] = []

    attribute_keys = _unique_sorted(
        [key for c in candidates for key in c.attributes if key not in IDENTITY_ATTRIBUTE_KEYS]
    )
    for key in attribute_keys:
        built.append((f"attr:{key}", _attribute_options(candidates, key)))

    if every_candidate_has_fitment:
        built.append(("make", _options_from_rows(rows, "make")))
        built.append(("model", _options_from_rows(rows, "model")))
        built.append(("year", _year_options(rows)))
    built.append(("mpn", _part_number_options(candidates)))
    built.append(("brand", _brand_options(candidates)))

    usable = [
        (facet, options)
        for facet, options in built
        if facet not in asked and _is_useful(options, len(candidates))
    ]
    if not usable:
        return None

    # Easiest to answer first, then strongest elimination, then fewest chips.
    usable.sort(
        key=lambda item: (_answerability(item[0]), _worst_case_remaining(item[1]), len(item[1]))
    )

    facet, options = usable[0]
    prompt, hint = prompt_for(facet)
    return Question(facet=facet, prompt=prompt, hint=hint, options=tuple(options))


def _decisive_visual_leader(candidates: list[ChatCandidate]) -> ChatCandidate | None:
    """Rank-1, but only when its lead over rank 2 is decisive. A single scan
    of the top two — a photo can have a clear favourite even when other
    candidates are bunched close together further down the list."""
    if len(candidates) < 2:
        return None
    leader, runner_up = candidates[0], candidates[1]
    return leader if leader.similarity - runner_up.similarity >= STRONG_SEPARATION_GAP else None


def detect_visual_mismatch(
    candidates: list[ChatCandidate],
    answers: list[Answer],
) -> VisualMismatch | None:
    """True when the answer trail has ruled out the candidate the photo most
    strongly favoured — the chat should not silently let a user's answers
    overrule what the image itself suggested.

    Only fires when the photo had a decisive opinion in the first place.
    Without that gate, this would fire on almost every ordinary session,
    since close scores are exactly why the chat exists.
    """
    leader = _decisive_visual_leader(candidates)
    if leader is None:
        return None
    survivors = apply_answers(candidates, answers)
    if not survivors or any(c.sku == leader.sku for c in survivors):
        return None
    return VisualMismatch(visual_leader=leader, best_survivor=survivors[0])


def collapse_fitment_years(vehicles: list[tuple[str, str, int]]) -> tuple[FitmentRange, ...]:
    """Folds the catalog's one-row-per-model-year fitment back into ranges.

    The importer expands "Ford Focus (2012–2018)" into seven rows of
    `(make, model, year)`. Questions want ranges, so consecutive years merge;
    a gap in the years still starts a new range — that gap is real fitment
    data, not noise. Mirrors `adaptVehicleCompatibility` in
    `frontend/src/adapters/productAdapter.ts`.
    """
    by_vehicle: dict[tuple[str, str], set[int]] = {}
    for make, model, year in vehicles:
        by_vehicle.setdefault((make, model), set()).add(year)

    merged: list[FitmentRange] = []
    for (make, model), years in by_vehicle.items():
        ordered = sorted(years)
        start = previous = ordered[0]
        for year in ordered[1:]:
            if year == previous + 1:
                previous = year
                continue
            merged.append(FitmentRange(make, model, start, previous))
            start = previous = year
        merged.append(FitmentRange(make, model, start, previous))
    return tuple(merged)
