import { formatAttributeLabel, formatAttributeValue } from '@/utils/attributes'
import type { IdentificationCandidate } from '@/types/identification'

/**
 * Turns "these three look identical, you pick" into a short series of answerable
 * questions.
 *
 * Visual similarity cannot separate parts that genuinely look alike — two brake
 * pad sets for different cars are the same object photographed twice. But the
 * catalog already knows what does separate them: fitment and brand. So instead of
 * asking the user to compare photos they have no way to judge, ask what they
 * actually know ("which vehicle?") and let each answer eliminate candidates.
 *
 * Questions are derived from catalog metadata rather than generated by Brain 4:
 * every option is guaranteed to correspond to real SKUs, an answer provably
 * narrows the set, and it works with the LLM switched off.
 */

/**
 * `attr:<key>` facets come from the product's `attributes` bag, whose keys vary
 * by category — a filter has `filter_style`, a pad has `friction_material`.
 */
export type FacetKey = 'make' | 'model' | 'year' | 'brand' | 'mpn' | `attr:${string}`

/**
 * The fitment rows an answer keeps in play.
 *
 * A product can fit several vehicles, so answering "Honda" must not only drop
 * Toyota-only candidates — it must also stop a surviving candidate's Toyota rows
 * from feeding the next question, or picking Honda would still offer "Camry".
 */
export interface RowFilter {
  make?: string
  model?: string
  yearStart?: number
  yearEnd?: number
}

export interface DisambiguationOption {
  /** What the user sees on the chip. */
  label: string
  /** SKUs still possible if this option is chosen. Never empty. */
  skus: string[]
  /** Constraint this option puts on fitment rows for later questions. */
  filter?: RowFilter
}

export interface DisambiguationQuestion {
  facet: FacetKey
  prompt: string
  /** Shown under the prompt — why this question is being asked. */
  hint: string
  options: DisambiguationOption[]
}

export interface DisambiguationAnswer {
  facet: FacetKey
  label: string
  skus: string[]
  filter?: RowFilter
}

/** One (SKU, vehicle) pair. Fitment is many-per-SKU, so questions filter rows, not products. */
interface FitmentRow {
  sku: string
  make: string
  model: string
  yearStart: number
  yearEnd: number
}

const PROMPTS: Record<string, { prompt: string; hint: string }> = {
  make: { prompt: 'Which vehicle is this part for?', hint: 'These candidates fit different makes.' },
  model: { prompt: 'Which model?', hint: 'Narrowing further by model.' },
  year: { prompt: 'Which model year?', hint: 'The remaining candidates cover different year ranges.' },
  mpn: {
    prompt: 'Is one of these numbers on the part?',
    hint: 'Usually stamped into the metal or printed on the old box.',
  },
  brand: {
    prompt: 'Do you know the part brand?',
    hint: 'Often stamped on the part or printed on the old packaging.',
  },
}

/**
 * Prompts for `attributes` keys. Anything not listed falls back to a humanized
 * key, so a new attribute added to the catalog asks a sensible question without
 * a frontend change.
 */
const ATTRIBUTE_PROMPTS: Record<string, { prompt: string; hint: string }> = {
  primary_colour: { prompt: 'What colour is it, mainly?', hint: 'The body, not the fittings.' },
  filter_style: { prompt: 'Is it a spin-on canister or a cartridge insert?', hint: 'Look at the shape.' },
  filter_shape: { prompt: 'What shape is the filter?', hint: '' },
  position: { prompt: 'Where does it fit on the vehicle?', hint: 'Front or rear axle.' },
  material: { prompt: 'What is it made of?', hint: '' },
  friction_material: { prompt: 'What is the friction material?', hint: 'Usually printed on the pad edge or box.' },
  damper_style: { prompt: 'Which of these does it look like?', hint: '' },
  manifold_style: { prompt: 'Which of these does it look like?', hint: '' },
  injector_type: { prompt: 'Which type of injector is it?', hint: '' },
  pump_style: { prompt: 'Which type of pump is it?', hint: '' },
  throttle_control: { prompt: 'Is it cable-operated or electronic?', hint: 'Look for a cable pulley or a plug.' },
  sold_as: { prompt: 'How many are in the set?', hint: '' },
  lug_count: { prompt: 'How many wheel studs does it have?', hint: 'Count the bolts on the flange.' },
  abs_sensor: { prompt: 'Does it have an ABS sensor?', hint: 'A wire running off the hub.' },
  wear_sensor: { prompt: 'Does it have a wear sensor?', hint: 'A small wire clipped to one pad.' },
  pulley_fitted: { prompt: 'Is the pulley already fitted?', hint: '' },
  integrated_reservoir: { prompt: 'Does it have a fluid reservoir on top?', hint: '' },
  catalytic_converter: { prompt: 'Does it include a catalytic converter?', hint: '' },
}



function promptFor(facet: FacetKey): { prompt: string; hint: string } {
  if (!facet.startsWith('attr:')) return PROMPTS[facet]
  const key = facet.slice('attr:'.length)
  return ATTRIBUTE_PROMPTS[key] ?? { prompt: `${formatAttributeLabel(key)}?`, hint: '' }
}

function fitmentRows(candidates: IdentificationCandidate[]): FitmentRow[] {
  return candidates.flatMap((candidate) =>
    candidate.compatibleVehicles.map((vehicle) => ({
      sku: candidate.sku,
      make: vehicle.make,
      model: vehicle.model,
      yearStart: vehicle.yearStart,
      yearEnd: vehicle.yearEnd,
    })),
  )
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b))
}

/** Options for a facet whose values are plain strings on the fitment row. */
function optionsFromRows(rows: FitmentRow[], key: 'make' | 'model'): DisambiguationOption[] {
  return uniqueSorted(rows.map((row) => row[key])).map((label) => ({
    label,
    skus: uniqueSorted(rows.filter((row) => row[key] === label).map((row) => row.sku)),
    filter: { [key]: label },
  }))
}

/** Rows still consistent with every answer given so far. */
function filterRows(rows: FitmentRow[], answers: DisambiguationAnswer[]): FitmentRow[] {
  return answers.reduce((current, answer) => {
    const filter = answer.filter
    if (!filter) return current
    return current.filter(
      (row) =>
        (filter.make === undefined || row.make === filter.make) &&
        (filter.model === undefined || row.model === filter.model) &&
        // Year answers are ranges; a row survives if its coverage overlaps.
        (filter.yearStart === undefined ||
          filter.yearEnd === undefined ||
          (row.yearStart <= filter.yearEnd && row.yearEnd >= filter.yearStart)),
    )
  }, rows)
}

/**
 * Year options as ranges rather than one chip per year.
 *
 * A year only distinguishes candidates where their coverage differs, so
 * consecutive years matching the same SKU set collapse into a single chip —
 * "2018–2022" and "2023–2024" rather than seven chips that mostly do nothing.
 */
function yearOptions(rows: FitmentRow[]): DisambiguationOption[] {
  if (rows.length === 0) return []
  const first = Math.min(...rows.map((row) => row.yearStart))
  const last = Math.max(...rows.map((row) => row.yearEnd))

  const runs: { start: number; end: number; skus: string[] }[] = []
  for (let year = first; year <= last; year += 1) {
    const skus = uniqueSorted(
      rows.filter((row) => year >= row.yearStart && year <= row.yearEnd).map((row) => row.sku),
    )
    if (skus.length === 0) continue
    const previous = runs.at(-1)
    const sameAsPrevious =
      previous && previous.end === year - 1 && previous.skus.join('|') === skus.join('|')
    if (sameAsPrevious) {
      previous.end = year
    } else {
      runs.push({ start: year, end: year, skus })
    }
  }

  return runs.map((run) => ({
    label: run.start === run.end ? `${run.start}` : `${run.start}–${run.end}`,
    skus: run.skus,
    filter: { yearStart: run.start, yearEnd: run.end },
  }))
}

function brandOptions(candidates: IdentificationCandidate[]): DisambiguationOption[] {
  return uniqueSorted(candidates.map((candidate) => candidate.brand)).map((label) => ({
    label,
    skus: uniqueSorted(candidates.filter((candidate) => candidate.brand === label).map((c) => c.sku)),
  }))
}

function partNumberOptions(candidates: IdentificationCandidate[]): DisambiguationOption[] {
  const numbered = candidates.filter((candidate) => candidate.manufacturerPartNumber)
  return uniqueSorted(numbered.map((candidate) => candidate.manufacturerPartNumber!)).map((label) => ({
    label,
    skus: uniqueSorted(
      numbered.filter((c) => c.manufacturerPartNumber === label).map((c) => c.sku),
    ),
  }))
}

/**
 * One option per distinct value of an attribute key.
 *
 * Only offered when every candidate carries the key: a product whose attribute
 * was never derived would otherwise be silently ruled out for having no value,
 * which is a data gap rather than a mismatch.
 */
function attributeOptions(
  candidates: IdentificationCandidate[],
  key: string,
): DisambiguationOption[] {
  if (!candidates.every((candidate) => candidate.attributes?.[key])) return []
  return uniqueSorted(candidates.map((candidate) => candidate.attributes[key])).map((value) => ({
    label: formatAttributeValue(value),
    skus: uniqueSorted(candidates.filter((c) => c.attributes[key] === value).map((c) => c.sku)),
  }))
}

function worstCaseRemaining(options: DisambiguationOption[]): number {
  return Math.max(...options.map((option) => option.skus.length))
}

/**
 * Worth asking if at least one answer rules something out.
 *
 * Deliberately not "every answer narrows it": a part fitting 2018-2024 against
 * one fitting 2018-2022 is only separated by picking 2023-24, and that question
 * is still the one worth asking.
 */
function isUseful(options: DisambiguationOption[], candidateCount: number): boolean {
  return options.length > 1 && Math.min(...options.map((o) => o.skus.length)) < candidateCount
}

/**
 * How readily a typical user can answer, lowest first.
 *
 * Ranking purely by elimination power puts brand first, because brand usually
 * splits the candidates perfectly — but someone photographing a part to find out
 * what it is is exactly the person who does not know its brand.
 *
 * The ordering follows what the user has in front of them. Visual attributes
 * come first: they are answered by looking at the part already in their hand
 * ("spin-on or cartridge?", "what colour is it?"), which needs no knowledge at
 * all. Then facts about their own car. Then the part number, which is decisive
 * but means hunting for stamped text. Brand last.
 *
 * Elimination power only orders facets within a tier; "Not sure" skips one.
 */
function answerability(facet: FacetKey): number {
  if (facet.startsWith('attr:')) return 0
  return { make: 1, model: 2, year: 3, mpn: 4, brand: 5 }[facet as 'make'] ?? 9
}

/**
 * The next question to ask, or null when the candidates are already resolved (or
 * nothing left can separate them — the caller should fall back to manual choice).
 *
 * Pass the answers given so far (not just their facets) so vehicle questions stay
 * consistent with each other, plus any facets the user skipped with "Not sure".
 */
export function nextQuestion(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[] = [],
  skipped: FacetKey[] = [],
): DisambiguationQuestion | null {
  const remaining = applyAnswers(candidates, answers)
  if (remaining.length < 2) return null

  const asked = [...answers.map((answer) => answer.facet), ...skipped]
  return questionFor(remaining, filterRows(fitmentRows(remaining), answers), asked)
}

function questionFor(
  candidates: IdentificationCandidate[],
  rows: FitmentRow[],
  asked: FacetKey[],
): DisambiguationQuestion | null {
  // A vehicle question can only eliminate safely when every candidate has
  // fitment on record. Otherwise "no rows" would look like "does not fit" and
  // silently rule out a product whose data is merely missing.
  const everyCandidateHasFitment = candidates.every((c) => c.compatibleVehicles.length > 0)

  const built: { facet: FacetKey; options: DisambiguationOption[] }[] = []

  // Every attribute key any candidate carries is a candidate question.
  // `?? {}` guards a candidate built before `attributes` existed (a cached API
  // response, say). Crashing the whole results page over a missing enrichment
  // would be a poor trade.
  const attributeKeys = uniqueSorted(candidates.flatMap((c) => Object.keys(c.attributes ?? {})))
  for (const key of attributeKeys) {
    built.push({ facet: `attr:${key}`, options: attributeOptions(candidates, key) })
  }

  if (everyCandidateHasFitment) {
    built.push({ facet: 'make', options: optionsFromRows(rows, 'make') })
    built.push({ facet: 'model', options: optionsFromRows(rows, 'model') })
    built.push({ facet: 'year', options: yearOptions(rows) })
  }
  built.push({ facet: 'mpn', options: partNumberOptions(candidates) })
  built.push({ facet: 'brand', options: brandOptions(candidates) })

  const usable = built
    .filter(({ facet }) => !asked.includes(facet))
    .filter(({ options }) => isUseful(options, candidates.length))

  if (usable.length === 0) return null

  // Easiest to answer first, then strongest elimination, then fewest chips.
  usable.sort(
    (a, b) =>
      answerability(a.facet) - answerability(b.facet) ||
      worstCaseRemaining(a.options) - worstCaseRemaining(b.options) ||
      a.options.length - b.options.length,
  )

  const best = usable[0]
  return { facet: best.facet, ...promptFor(best.facet), options: best.options }
}

/** Candidates still possible after every answer so far. */
export function applyAnswers(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[],
): IdentificationCandidate[] {
  return answers.reduce(
    (remaining, answer) => remaining.filter((candidate) => answer.skus.includes(candidate.sku)),
    candidates,
  )
}

/**
 * True when questions could help at all. Used to decide between the guided flow
 * and the plain "compare them yourself" panel.
 */
export function canDisambiguate(candidates: IdentificationCandidate[]): boolean {
  return nextQuestion(candidates) !== null
}
