import type { IdentificationCandidate } from '@/types/identification'

/**
 * Turns "these three look identical, you pick" into a short series of answerable
 * questions.
 *
 * Visual similarity cannot separate parts that genuinely look alike — two brake
 * pad sets for different cars are the same object photographed twice. But the
 * catalog already knows what does separate them: fitment and brand. So instead of
 * asking the user to compare photos they have no way to judge, ask what they
 * actually know ("which vehicle?") and let each answer eliminate candidates.
 *
 * Questions are derived from catalog metadata rather than generated by Brain 4:
 * every option is guaranteed to correspond to real SKUs, an answer provably
 * narrows the set, and it works with the LLM switched off.
 */

export type FacetKey = 'make' | 'model' | 'year' | 'brand'

/**
 * The fitment rows an answer keeps in play.
 *
 * A product can fit several vehicles, so answering "Honda" must not only drop
 * Toyota-only candidates — it must also stop a surviving candidate's Toyota rows
 * from feeding the next question, or picking Honda would still offer "Camry".
 */
export interface RowFilter {
  make?: string
  model?: string
  yearStart?: number
  yearEnd?: number
}

export interface DisambiguationOption {
  /** What the user sees on the chip. */
  label: string
  /** SKUs still possible if this option is chosen. Never empty. */
  skus: string[]
  /** Constraint this option puts on fitment rows for later questions. */
  filter?: RowFilter
}

export interface DisambiguationQuestion {
  facet: FacetKey
  prompt: string
  /** Shown under the prompt — why this question is being asked. */
  hint: string
  options: DisambiguationOption[]
}

export interface DisambiguationAnswer {
  facet: FacetKey
  label: string
  skus: string[]
  filter?: RowFilter
}

/** One (SKU, vehicle) pair. Fitment is many-per-SKU, so questions filter rows, not products. */
interface FitmentRow {
  sku: string
  make: string
  model: string
  yearStart: number
  yearEnd: number
}

const PROMPTS: Record<FacetKey, { prompt: string; hint: string }> = {
  make: { prompt: 'Which vehicle is this part for?', hint: 'These candidates fit different makes.' },
  model: { prompt: 'Which model?', hint: 'Narrowing further by model.' },
  year: { prompt: 'Which model year?', hint: 'The remaining candidates cover different year ranges.' },
  brand: {
    prompt: 'Do you know the part brand?',
    hint: 'Often stamped on the part or printed on the old packaging.',
  },
}

function fitmentRows(candidates: IdentificationCandidate[]): FitmentRow[] {
  return candidates.flatMap((candidate) =>
    candidate.compatibleVehicles.map((vehicle) => ({
      sku: candidate.sku,
      make: vehicle.make,
      model: vehicle.model,
      yearStart: vehicle.yearStart,
      yearEnd: vehicle.yearEnd,
    })),
  )
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b))
}

/** Options for a facet whose values are plain strings on the fitment row. */
function optionsFromRows(rows: FitmentRow[], key: 'make' | 'model'): DisambiguationOption[] {
  return uniqueSorted(rows.map((row) => row[key])).map((label) => ({
    label,
    skus: uniqueSorted(rows.filter((row) => row[key] === label).map((row) => row.sku)),
    filter: { [key]: label },
  }))
}

/** Rows still consistent with every answer given so far. */
function filterRows(rows: FitmentRow[], answers: DisambiguationAnswer[]): FitmentRow[] {
  return answers.reduce((current, answer) => {
    const filter = answer.filter
    if (!filter) return current
    return current.filter(
      (row) =>
        (filter.make === undefined || row.make === filter.make) &&
        (filter.model === undefined || row.model === filter.model) &&
        // Year answers are ranges; a row survives if its coverage overlaps.
        (filter.yearStart === undefined ||
          filter.yearEnd === undefined ||
          (row.yearStart <= filter.yearEnd && row.yearEnd >= filter.yearStart)),
    )
  }, rows)
}

/**
 * Year options as ranges rather than one chip per year.
 *
 * A year only distinguishes candidates where their coverage differs, so
 * consecutive years matching the same SKU set collapse into a single chip —
 * "2018–2022" and "2023–2024" rather than seven chips that mostly do nothing.
 */
function yearOptions(rows: FitmentRow[]): DisambiguationOption[] {
  if (rows.length === 0) return []
  const first = Math.min(...rows.map((row) => row.yearStart))
  const last = Math.max(...rows.map((row) => row.yearEnd))

  const runs: { start: number; end: number; skus: string[] }[] = []
  for (let year = first; year <= last; year += 1) {
    const skus = uniqueSorted(
      rows.filter((row) => year >= row.yearStart && year <= row.yearEnd).map((row) => row.sku),
    )
    if (skus.length === 0) continue
    const previous = runs.at(-1)
    const sameAsPrevious =
      previous && previous.end === year - 1 && previous.skus.join('|') === skus.join('|')
    if (sameAsPrevious) {
      previous.end = year
    } else {
      runs.push({ start: year, end: year, skus })
    }
  }

  return runs.map((run) => ({
    label: run.start === run.end ? `${run.start}` : `${run.start}–${run.end}`,
    skus: run.skus,
    filter: { yearStart: run.start, yearEnd: run.end },
  }))
}

function brandOptions(candidates: IdentificationCandidate[]): DisambiguationOption[] {
  return uniqueSorted(candidates.map((candidate) => candidate.brand)).map((label) => ({
    label,
    skus: uniqueSorted(candidates.filter((candidate) => candidate.brand === label).map((c) => c.sku)),
  }))
}

function worstCaseRemaining(options: DisambiguationOption[]): number {
  return Math.max(...options.map((option) => option.skus.length))
}

/**
 * Worth asking if at least one answer rules something out.
 *
 * Deliberately not "every answer narrows it": a part fitting 2018-2024 against
 * one fitting 2018-2022 is only separated by picking 2023-24, and that question
 * is still the one worth asking.
 */
function isUseful(options: DisambiguationOption[], candidateCount: number): boolean {
  return options.length > 1 && Math.min(...options.map((o) => o.skus.length)) < candidateCount
}

/**
 * How readily a typical user can answer, lowest first.
 *
 * Ranking purely by elimination power puts brand first, because brand usually
 * splits the candidates perfectly — but someone photographing a part to find out
 * what it is is exactly the person who does not know its brand. Facts about
 * their own car they do know. Elimination power only orders facets within a
 * tier; "Not sure" skips to the next one.
 */
const ANSWERABILITY: Record<FacetKey, number> = { make: 0, model: 1, year: 2, brand: 3 }

/**
 * The next question to ask, or null when the candidates are already resolved (or
 * nothing left can separate them — the caller should fall back to manual choice).
 *
 * Pass the answers given so far (not just their facets) so vehicle questions stay
 * consistent with each other, plus any facets the user skipped with "Not sure".
 */
export function nextQuestion(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[] = [],
  skipped: FacetKey[] = [],
): DisambiguationQuestion | null {
  const remaining = applyAnswers(candidates, answers)
  if (remaining.length < 2) return null

  const asked = [...answers.map((answer) => answer.facet), ...skipped]
  return questionFor(remaining, filterRows(fitmentRows(remaining), answers), asked)
}

function questionFor(
  candidates: IdentificationCandidate[],
  rows: FitmentRow[],
  asked: FacetKey[],
): DisambiguationQuestion | null {
  // A vehicle question can only eliminate safely when every candidate has
  // fitment on record. Otherwise "no rows" would look like "does not fit" and
  // silently rule out a product whose data is merely missing.
  const everyCandidateHasFitment = candidates.every((c) => c.compatibleVehicles.length > 0)

  const built: { facet: FacetKey; options: DisambiguationOption[] }[] = []
  if (everyCandidateHasFitment) {
    built.push({ facet: 'make', options: optionsFromRows(rows, 'make') })
    built.push({ facet: 'model', options: optionsFromRows(rows, 'model') })
    built.push({ facet: 'year', options: yearOptions(rows) })
  }
  built.push({ facet: 'brand', options: brandOptions(candidates) })

  const usable = built
    .filter(({ facet }) => !asked.includes(facet))
    .filter(({ options }) => isUseful(options, candidates.length))

  if (usable.length === 0) return null

  // Easiest to answer first, then strongest elimination, then fewest chips.
  usable.sort(
    (a, b) =>
      ANSWERABILITY[a.facet] - ANSWERABILITY[b.facet] ||
      worstCaseRemaining(a.options) - worstCaseRemaining(b.options) ||
      a.options.length - b.options.length,
  )

  const best = usable[0]
  return { facet: best.facet, ...PROMPTS[best.facet], options: best.options }
}

/** Candidates still possible after every answer so far. */
export function applyAnswers(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[],
): IdentificationCandidate[] {
  return answers.reduce(
    (remaining, answer) => remaining.filter((candidate) => answer.skus.includes(candidate.sku)),
    candidates,
  )
}

/**
 * True when questions could help at all. Used to decide between the guided flow
 * and the plain "compare them yourself" panel.
 */
export function canDisambiguate(candidates: IdentificationCandidate[]): boolean {
  return nextQuestion(candidates) !== null
}
