import { formatAttributeLabel } from '@/utils/attributes'
import { STRONG_SEPARATION_GAP } from './identificationService'
import type { IdentificationCandidate } from '@/types/identification'

/**
 * Turns "these three look identical, you pick" into a short series of answerable
 * questions.
 *
 * Visual similarity cannot separate parts that genuinely look alike - two brake
 * pad sets for different cars are the same object photographed twice. But the
 * catalog already knows what does separate them: fitment and brand. So instead of
 * asking the user to compare photos they have no way to judge, ask what they
 * actually know ("which vehicle?") and let each answer eliminate candidates.
 *
 * Questions are derived from catalog metadata rather than generated by Brain 4:
 * every option is guaranteed to correspond to real SKUs, an answer provably
 * narrows the set, and it works with the LLM switched off.
 */

/**
 * `attr:<key>` facets come from the product's `attributes` bag, whose keys vary
 * by category - a filter has `filter_style`, a pad has `friction_material`.
 */
export type FacetKey = 'make' | 'model' | 'year' | 'brand' | 'mpn' | `attr:${string}`

/**
 * The fitment rows an answer keeps in play.
 *
 * A product can fit several vehicles, so answering "Honda" must not only drop
 * Toyota-only candidates - it must also stop a surviving candidate's Toyota rows
 * from feeding the next question, or picking Honda would still offer "Camry".
 */
export interface RowFilter {
  make?: string
  model?: string
  yearStart?: number
  yearEnd?: number
}

export interface DisambiguationOption {
  /** What the user sees on the chip. */
  label: string
  /** SKUs still possible if this option is chosen. Empty only when `escape`. */
  skus: string[]
  /** Constraint this option puts on fitment rows for later questions. */
  filter?: RowFilter
  /**
   * "None of these" - the answer rules every candidate out, so the honest
   * response is that we do not stock the part.
   *
   * This is the only reliable refusal the system has. Measured on 200 queries,
   * no signal computed from the photograph separates a product we stock from
   * its nearest lookalike that we do not: similarity and top-2 margin barely
   * beat chance, and SIFT/RANSAC verification is marginally inverted (median 12
   * inliers for the wrong rival against 11 for the right answer). An unstocked
   * ball mount resembles a stocked one because it is the same shape.
   *
   * The brand is the information the shape does not carry, and the customer can
   * read it off the part - so asking beats any amount of further modelling.
   */
  escape?: true
}

export interface DisambiguationQuestion {
  facet: FacetKey
  prompt: string
  /** Shown under the prompt - why this question is being asked. */
  hint: string
  options: DisambiguationOption[]
}

export interface DisambiguationAnswer {
  facet: FacetKey
  label: string
  skus: string[]
  filter?: RowFilter
}

/** One (SKU, vehicle) pair. Fitment is many-per-SKU, so questions filter rows, not products. */
interface FitmentRow {
  sku: string
  make: string
  model: string
  yearStart: number
  yearEnd: number
}

const PROMPTS: Record<string, { prompt: string; hint: string }> = {
  make: { prompt: 'Which vehicle is this for?', hint: 'These candidates fit different makes.' },
  model: { prompt: 'Which model?', hint: 'Narrowing further by model.' },
  year: { prompt: 'Which model year?', hint: 'The remaining candidates cover different year ranges.' },
  mpn: {
    prompt: 'Is one of these numbers on the part?',
    hint: 'Usually stamped into the metal or printed on the old box.',
  },
  brand: {
    prompt: 'Do you know the part brand?',
    hint: 'Often stamped on the part or printed on the old packaging.',
  },
}

/**
 * Prompts for `attributes` keys. Anything not listed falls back to a humanized
 * key, so a new attribute added to the catalog asks a sensible question without
 * a frontend change.
 */
const ATTRIBUTE_PROMPTS: Record<string, { prompt: string; hint: string }> = {
  watts: { prompt: 'What wattage is it?', hint: 'Usually stamped on the element or its collar.' },
  voltage: { prompt: 'What voltage?', hint: 'Printed next to the wattage.' },
  drop: { prompt: 'How far down does the bar drop?', hint: 'Measure from the top of the shank to the ball hole.' },
  rise: { prompt: 'How far up does the bar rise?', hint: 'For a ball mount fitted upside down.' },
  ball_diameter: { prompt: 'How wide is the ball?', hint: 'Measure across the widest point - usually stamped on top.' },
  shank_size: { prompt: 'How wide is the square shank?', hint: 'The bar that slides into the receiver.' },
  receiver_size: { prompt: 'What size is your receiver opening?', hint: 'Measure the square hole - commonly 2 or 2½ inch.' },
  capacity: { prompt: 'What weight is it rated for?', hint: 'Usually stamped on the part.' },
  tow_capacity: { prompt: 'What towing capacity?', hint: 'Stamped on the part or in its paperwork.' },
  length: { prompt: 'How long is it?', hint: 'Measure end to end.' },
  width: { prompt: 'How wide is it?', hint: '' },
  height: { prompt: 'How tall is it?', hint: '' },
  hub_face: { prompt: 'What is the hub face measurement?', hint: 'Measured between the hub faces.' },
  bolt_pattern: { prompt: 'What is the bolt pattern?', hint: 'Count the studs and measure across the circle.' },
  lug_count: { prompt: 'How many studs does it have?', hint: 'Count the bolts on the flange.' },
  wire_count: { prompt: 'How many wires or pins does the plug have?', hint: 'Count the pins in the connector.' },
  connector_type: { prompt: 'What type of connector?', hint: 'Look at the shape of the plug.' },
  material: { prompt: 'What is it made of?', hint: '' },
  finish: { prompt: 'What finish does it have?', hint: 'Zinc is dull silver; powder coat is usually black.' },
  fits: { prompt: 'What does it fit?', hint: 'What the part attaches to.' },
  fitment: { prompt: 'What does it fit?', hint: 'For example a 2 inch receiver.' },
}

/**
 * Attribute keys never worth asking about.
 *
 * Some carry no signal - `special_order` is "No" on 10,631 of RigidHitch's
 * 10,813 products, so it can never eliminate anything. Others must not reach a
 * customer at all: `installation_instructions` holds an internal
 * `\\fileserver\...` path, and `keyword` holds internal codes.
 */
const ATTRIBUTE_BLOCKLIST = new Set([
  'special_order',
  'installation_instructions',
  'keyword',
  'warranty',
  'suggested_wiring',
  'made_in',
])

/** Exposed so the results UI can replay a past answer's question text. */
export function promptFor(facet: FacetKey): { prompt: string; hint: string } {
  if (!facet.startsWith('attr:')) return PROMPTS[facet]
  const key = facet.slice('attr:'.length)
  return (
    ATTRIBUTE_PROMPTS[key] ?? {
      prompt: `What's the ${formatAttributeLabel(key).toLowerCase()}?`,
      hint: 'Compare against the part in your photo.',
    }
  )
}

function fitmentRows(candidates: IdentificationCandidate[]): FitmentRow[] {
  return candidates.flatMap((candidate) =>
    candidate.compatibleVehicles.map((vehicle) => ({
      sku: candidate.sku,
      make: vehicle.make,
      model: vehicle.model,
      yearStart: vehicle.yearStart,
      yearEnd: vehicle.yearEnd,
    })),
  )
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b))
}

/** Options for a facet whose values are plain strings on the fitment row. */
function optionsFromRows(rows: FitmentRow[], key: 'make' | 'model'): DisambiguationOption[] {
  return uniqueSorted(rows.map((row) => row[key])).map((label) => ({
    label,
    skus: uniqueSorted(rows.filter((row) => row[key] === label).map((row) => row.sku)),
    filter: { [key]: label },
  }))
}

/** Rows still consistent with every answer given so far. */
function filterRows(rows: FitmentRow[], answers: DisambiguationAnswer[]): FitmentRow[] {
  return answers.reduce((current, answer) => {
    const filter = answer.filter
    if (!filter) return current
    return current.filter(
      (row) =>
        (filter.make === undefined || row.make === filter.make) &&
        (filter.model === undefined || row.model === filter.model) &&
        // Year answers are ranges; a row survives if its coverage overlaps.
        (filter.yearStart === undefined ||
          filter.yearEnd === undefined ||
          (row.yearStart <= filter.yearEnd && row.yearEnd >= filter.yearStart)),
    )
  }, rows)
}

/**
 * Year options as ranges rather than one chip per year.
 *
 * A year only distinguishes candidates where their coverage differs, so
 * consecutive years matching the same SKU set collapse into a single chip -
 * "2018–2022" and "2023–2024" rather than seven chips that mostly do nothing.
 */
function yearOptions(rows: FitmentRow[]): DisambiguationOption[] {
  if (rows.length === 0) return []
  const first = Math.min(...rows.map((row) => row.yearStart))
  const last = Math.max(...rows.map((row) => row.yearEnd))

  const runs: { start: number; end: number; skus: string[] }[] = []
  for (let year = first; year <= last; year += 1) {
    const skus = uniqueSorted(
      rows.filter((row) => year >= row.yearStart && year <= row.yearEnd).map((row) => row.sku),
    )
    if (skus.length === 0) continue
    const previous = runs.at(-1)
    const sameAsPrevious =
      previous && previous.end === year - 1 && previous.skus.join('|') === skus.join('|')
    if (sameAsPrevious) {
      previous.end = year
    } else {
      runs.push({ start: year, end: year, skus })
    }
  }

  return runs.map((run) => ({
    label: run.start === run.end ? `${run.start}` : `${run.start}–${run.end}`,
    skus: run.skus,
    filter: { yearStart: run.start, yearEnd: run.end },
  }))
}

function brandOptions(candidates: IdentificationCandidate[]): DisambiguationOption[] {
  const brands = uniqueSorted(candidates.map((candidate) => candidate.brand)).map((label) => ({
    label,
    skus: uniqueSorted(candidates.filter((candidate) => candidate.brand === label).map((c) => c.sku)),
  }))
  // The escape is what makes this question worth asking even when every
  // candidate shares one brand: it cannot narrow the shortlist, but it can rule
  // the whole shortlist out, which nothing else here can.
  return [...brands, { label: 'A different brand', skus: [], escape: true as const }]
}

/**
 * Attribute keys worth considering as a question for this set of candidates.
 *
 * Every candidate must carry the key - a missing attribute means "unknown",
 * not "different", and answering would silently rule out a product whose data
 * is merely incomplete. That is the same trap the fitment check avoids.
 */
/**
 * Attribute keys worth asking about: recorded on at least two candidates, and
 * not the same value on all of them.
 *
 * Requiring *every* candidate to carry the key was too strict, and it blocked
 * the question that mattered most. Five inflatable truck toppers differing only
 * by bed length - 4½ ft, 5 ft, 6 ft, 6 ft 4 in - all record `bed_length` except
 * one, whose catalogue entry simply omits it. That single gap silenced the one
 * question a customer could actually answer, about a dimension no photograph
 * can show. `answerFor` handles the gap instead, by never ruling out a product
 * whose data is merely missing.
 */
function attributeKeys(candidates: IdentificationCandidate[]): string[] {
  if (candidates.length < 2) return []
  const keys = new Set(candidates.flatMap((c) => Object.keys(c.attributes ?? {})))
  return [...keys]
    .filter((key) => !ATTRIBUTE_BLOCKLIST.has(key))
    .filter((key) => {
      const values = candidates
        .map((c) => c.attributes?.[key])
        .filter((v): v is string => Boolean(v))
      return values.length >= 2 && new Set(values).size >= 2
    })
    .sort()
}

function attributeOptions(
  candidates: IdentificationCandidate[],
  key: string,
): DisambiguationOption[] {
  // A product that does not record this attribute survives every answer. Its
  // data being absent is not evidence against it, and dropping it would let a
  // hole in the catalogue quietly delete the right product from the shortlist.
  const unknown = candidates.filter((c) => !c.attributes?.[key]).map((c) => c.sku)
  const values = uniqueSorted(
    candidates.map((c) => c.attributes?.[key]).filter((v): v is string => Boolean(v)),
  )
  return values.map((label) => ({
    label,
    skus: uniqueSorted([
      ...candidates.filter((c) => c.attributes?.[key] === label).map((c) => c.sku),
      ...unknown,
    ]),
  }))
}

function partNumberOptions(candidates: IdentificationCandidate[]): DisambiguationOption[] {
  const numbered = candidates.filter((candidate) => candidate.manufacturerPartNumber)
  return uniqueSorted(numbered.map((candidate) => candidate.manufacturerPartNumber!)).map((label) => ({
    label,
    skus: uniqueSorted(
      numbered.filter((c) => c.manufacturerPartNumber === label).map((c) => c.sku),
    ),
  }))
}

function worstCaseRemaining(options: DisambiguationOption[]): number {
  return Math.max(...options.map((option) => option.skus.length))
}

/**
 * Worth asking if at least one answer rules something out.
 *
 * Deliberately not "every answer narrows it": a part fitting 2018-2024 against
 * one fitting 2018-2022 is only separated by picking 2023-24, and that question
 * is still the one worth asking.
 */
function isUseful(options: DisambiguationOption[], candidateCount: number): boolean {
  // Escapes are ignored here on purpose. One is attached to a question that is
  // already worth asking, but it must never be the reason for asking: an escape
  // narrows nothing, and counting it would make every question look useful and
  // interrogate the customer after a perfectly decisive match. The "none of
  // these" route out of an all-one-brand shortlist is offered on the results
  // page instead, where it costs no extra question.
  const narrowing = options.filter((option) => !option.escape)
  return narrowing.length > 1 && Math.min(...narrowing.map((o) => o.skus.length)) < candidateCount
}

/**
 * How readily a typical user can answer, lowest first.
 *
 * Ranking purely by elimination power puts brand first, because brand usually
 * splits the candidates perfectly - but someone photographing a part to find out
 * what it is is exactly the person who does not know its brand.
 *
 * The ordering follows what the user has in front of them. Visual attributes
 * come first: they are answered by looking at the part already in their hand
 * ("spin-on or cartridge?", "what colour is it?"), which needs no knowledge at
 * all. Then facts about their own car. Then the part number, which is decisive
 * but means hunting for stamped text. Brand last.
 *
 * Elimination power only orders facets within a tier; "Not sure" skips one.
 */
/**
 * Physical dimensions - answerable from the part itself, with a tape measure
 * if the label has worn off.
 */
const MEASURABLE = new Set([
  'drop', 'rise', 'length', 'width', 'height',
  'ball_diameter', 'shank_size', 'receiver_size', 'hub_face', 'bolt_pattern',
  'lug_count', 'wire_count',
])

/**
 * Ratings - printed on a plate or sticker and nowhere else. Unanswerable once
 * that wears off, and easy to guess at wrongly.
 */
const RATINGS = new Set([
  'capacity', 'tow_capacity', 'tongue_weight', 'gross_weight', 'load_rating',
])

/**
 * How reliably a customer can answer, lowest asked first.
 *
 * Dimensions come first because they are always recoverable: a 2 inch drop can
 * be measured whether or not the sticker survived. Ratings come last of the
 * attributes, because a wrong guess there is worse than no question at all -
 * it walks the customer to a confidently wrong product.
 */
function answerability(facet: FacetKey): number {
  if (facet.startsWith('attr:')) {
    const key = facet.slice('attr:'.length)
    if (MEASURABLE.has(key)) return 0
    if (RATINGS.has(key)) return 4
    return 1 // stamped values: wattage, voltage, finish
  }
  return { brand: 2, mpn: 3, make: 5, model: 6, year: 7 }[facet as 'brand'] ?? 9
}

/**
 * The next question to ask, or null when the candidates are already resolved (or
 * nothing left can separate them - the caller should fall back to manual choice).
 *
 * Pass the answers given so far (not just their facets) so vehicle questions stay
 * consistent with each other, plus any facets the user skipped with "Not sure".
 */
export function nextQuestion(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[] = [],
  skipped: FacetKey[] = [],
): DisambiguationQuestion | null {
  const remaining = applyAnswers(candidates, answers)
  if (remaining.length < 2) return null

  const asked = [...answers.map((answer) => answer.facet), ...skipped]
  return questionFor(remaining, filterRows(fitmentRows(remaining), answers), asked)
}

function questionFor(
  candidates: IdentificationCandidate[],
  rows: FitmentRow[],
  asked: FacetKey[],
): DisambiguationQuestion | null {
  // A vehicle question can only eliminate safely when every candidate has
  // fitment on record. Otherwise "no rows" would look like "does not fit" and
  // silently rule out a product whose data is merely missing.
  const everyCandidateHasFitment = candidates.every((c) => c.compatibleVehicles.length > 0)

  const built: { facet: FacetKey; options: DisambiguationOption[] }[] = []

  // Only ever ask what the photograph genuinely cannot answer. The similarity
  // search has already ranked on appearance, so re-asking about shape or
  // colour would be friction rather than information.
  //
  // For this catalogue that means the *specifications*: wattage, drop height,
  // ball diameter, capacity. A 1000W element and a 1500W one are the same
  // object to a camera; so are a 2 inch drop ball mount and a 3 inch one.
  // Those differences are invisible in a photo and recorded in the data, which
  // makes them the only questions worth a customer's time.
  if (everyCandidateHasFitment) {
    built.push({ facet: 'make', options: optionsFromRows(rows, 'make') })
    built.push({ facet: 'model', options: optionsFromRows(rows, 'model') })
    built.push({ facet: 'year', options: yearOptions(rows) })
  }
  for (const key of attributeKeys(candidates)) {
    built.push({ facet: `attr:${key}`, options: attributeOptions(candidates, key) })
  }
  built.push({ facet: 'mpn', options: partNumberOptions(candidates) })
  built.push({ facet: 'brand', options: brandOptions(candidates) })

  const usable = built
    .filter(({ facet }) => !asked.includes(facet))
    .filter(({ options }) => isUseful(options, candidates.length))

  if (usable.length === 0) return null

  // Easiest to answer first, then strongest elimination, then fewest chips.
  usable.sort(
    (a, b) =>
      answerability(a.facet) - answerability(b.facet) ||
      worstCaseRemaining(a.options) - worstCaseRemaining(b.options) ||
      a.options.length - b.options.length,
  )

  const best = usable[0]
  return { facet: best.facet, ...promptFor(best.facet), options: best.options }
}

/** Candidates still possible after every answer so far. */
export function applyAnswers(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[],
): IdentificationCandidate[] {
  return answers.reduce(
    (remaining, answer) => remaining.filter((candidate) => answer.skus.includes(candidate.sku)),
    candidates,
  )
}

/**
 * True when questions could help at all. Used to decide whether the guided
 * flow runs before images are revealed, or there is nothing to ask and the
 * results page can reveal them immediately.
 */
export function canDisambiguate(candidates: IdentificationCandidate[]): boolean {
  return nextQuestion(candidates) !== null
}

/**
 * True when the answers have eliminated every candidate - the customer took an
 * escape, so we do not stock this part.
 *
 * Distinct from "narrowed to one": both leave `nextQuestion` with nothing to
 * ask, but one is an answer and the other is a refusal, and showing the wrong
 * one is exactly the failure this whole path exists to prevent.
 */
export function isRuledOut(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[],
): boolean {
  return candidates.length > 0 && applyAnswers(candidates, answers).length === 0
}

/**
 * Rank-1, but only when its lead over rank 2 is decisive (the same
 * `STRONG_SEPARATION_GAP` bar the AI match summary uses for "strong
 * separation"). A single scan of top two, not "does anything separate the
 * whole field" - a photo can have a clear favorite even when three other
 * candidates are bunched close together further down the list.
 */
function decisiveVisualLeader(candidates: IdentificationCandidate[]): IdentificationCandidate | null {
  if (candidates.length < 2) return null
  const [leader, runnerUp] = candidates
  return leader.similarity - runnerUp.similarity >= STRONG_SEPARATION_GAP ? leader : null
}

/**
 * True when `sku` is the photo's own decisive pick - i.e. presenting it as a
 * confident match doesn't overstate what the image search actually found.
 * Used to tell "98% and clearly ahead of everything else" apart from "98%,
 * but so is the runner-up" - a raw similarity number alone can't.
 */
export function isDecisiveVisualMatch(candidates: IdentificationCandidate[], sku: string): boolean {
  return decisiveVisualLeader(candidates)?.sku === sku
}

export interface VisualMismatch {
  /** The candidate the photo alone would pick - rank 1, when its lead over rank 2 is decisive. */
  visualLeader: IdentificationCandidate
  /** Highest-similarity candidate still possible after the current answer trail. */
  bestSurvivor: IdentificationCandidate
}

/**
 * True when the answer trail has ruled out the candidate the photo most
 * strongly favored - the guided flow should not silently let a user's
 * answers overrule what the image itself suggested.
 *
 * Only fires when the photo had a decisive opinion in the first place.
 * Without that gate, this would fire on almost every ordinary
 * disambiguation session, since close scores are exactly why the flow
 * exists - the warning would drown itself out.
 */
export function detectVisualMismatch(
  candidates: IdentificationCandidate[],
  answers: DisambiguationAnswer[],
): VisualMismatch | null {
  const leader = decisiveVisualLeader(candidates)
  if (!leader) return null
  const survivors = applyAnswers(candidates, answers)
  if (survivors.length === 0 || survivors.some((c) => c.sku === leader.sku)) return null
  return { visualLeader: leader, bestSurvivor: survivors[0] }
}
